### ISSUE TITLE
BK - Foto de perfil

### ISSUE THREAD

**Issue by AbreuY** [AlexanderDeMatteo/proyecto-finale#22]
- [x] [BUG] Guardar y actualizar foto de perfil al cargarla. Y enlazar con el avatar. (**Resuelto**: Se actualizó el método y el endpoint, al igual que la función del Frontend para cargar las imágenes en la base de datos y mostrar la misma para cada usuario)

**Comment by Jesuspestana01** [comment]
**Resuelto**: Se actualizó el método y el endpoint, al igual que la función del Frontend para cargar las imágenes en la base de datos y mostrar la misma para cada usuario.
